import json
import os

# SIMULATION
DEFAULT_MAX_STEPS = 200
DEFAULT_MAX_ERRORS = 10
DEFAULT_SEED = 300
DEFAULT_MAX_CONCURRENCY = 3
DEFAULT_NUM_TRIALS = 1
DEFAULT_SAVE_TO = None
DEFAULT_LOG_LEVEL = "ERROR"

# LLM
DEFAULT_AGENT_IMPLEMENTATION = "llm_agent"
DEFAULT_USER_IMPLEMENTATION = "user_simulator"
DEFAULT_LLM_AGENT = "gpt-4.1"
DEFAULT_LLM_USER = "gpt-4.1"
DEFAULT_LLM_TEMPERATURE_AGENT = 0.0
DEFAULT_LLM_TEMPERATURE_USER = 0.0
DEFAULT_LLM_ARGS_AGENT = json.loads(
    os.getenv('DEFAULT_LLM_ARGS_AGENT', '{}')
) or {
    "temperature": DEFAULT_LLM_TEMPERATURE_AGENT
}
DEFAULT_LLM_ARGS_USER = json.loads(
    os.getenv('DEFAULT_LLM_ARGS_USER', '{}')
) or {
    "temperature": DEFAULT_LLM_TEMPERATURE_USER
}

DEFAULT_LLM_NL_ASSERTIONS = os.getenv(
    'DEFAULT_LLM_NL_ASSERTIONS', "gpt-4o-mini"
)
DEFAULT_LLM_NL_ASSERTIONS_TEMPERATURE = 0.0
DEFAULT_LLM_NL_ASSERTIONS_ARGS = json.loads(
    os.getenv('DEFAULT_LLM_NL_ASSERTIONS_ARGS', "{}")
) or {"temperature": DEFAULT_LLM_NL_ASSERTIONS_TEMPERATURE}

DEFAULT_LLM_ENV_INTERFACE = os.getenv('DEFAULT_LLM_ENV_INTERFACE', "gpt-4.1")
DEFAULT_LLM_ENV_INTERFACE_TEMPERATURE = 0.0
DEFAULT_LLM_ENV_INTERFACE_ARGS = json.loads(
    os.getenv('DEFAULT_LLM_ENV_INTERFACE_ARGS', "{}")
) or {"temperature": DEFAULT_LLM_ENV_INTERFACE_TEMPERATURE}

# LITELLM
DEFAULT_MAX_RETRIES = 3
LLM_CACHE_ENABLED = False
DEFAULT_LLM_CACHE_TYPE = "redis"

# REDIS CACHE
REDIS_HOST = "localhost"
REDIS_PORT = 6379
REDIS_PASSWORD = ""
REDIS_PREFIX = "tau2"
REDIS_CACHE_VERSION = "v1"
REDIS_CACHE_TTL = 60 * 60 * 24 * 30

# LANGFUSE
# If True, make sure all the env variables are set for langfuse.
USE_LANGFUSE = False

# API
API_PORT = 8000
